// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	__ "go-practice/gRPC/protogen"

	mock "github.com/stretchr/testify/mock"
)

// IgRPC is an autogenerated mock type for the IgRPC type
type IgRPC struct {
	mock.Mock
}

// CreateServer provides a mock function with given fields:
func (_m *IgRPC) CreateServer() {
	_m.Called()
}

// sayHello provides a mock function with given fields: request
func (_m *IgRPC) sayHello(request *__.HelloRequest) *__.HelloReply {
	ret := _m.Called(request)

	var r0 *__.HelloReply
	if rf, ok := ret.Get(0).(func(*__.HelloRequest) *__.HelloReply); ok {
		r0 = rf(request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*__.HelloReply)
		}
	}

	return r0
}

// RunServer provides a mock function with given fields:
func (_m *IgRPC) RunServer() {
	_m.Called()
}
